
desc "Create on Developer Portal and App Store Connect"
  lane :create_app do
create_app_online # produce
  end

platform :ios do
  desc "Sync signing"
  lane :signing do
  end

  desc "Build binary"
  lane :build do
	signing
  end

  desc "release"
  lane :release do
	build
  end
end
